version: '3'
services:
  app:
    build:
      context: .
    working_dir: /deploy/app/
    volumes:
      - ./src/backend/server/drones.db:/deploy/app/src/backend/server/drones.db
    ports:
      - '18000:18000'
    networks:
      - web_nw

  nginx:
    image: "nginx:mainline"
    volumes:
      - ./src/conf.d:/etc/nginx/conf.d
      - ./src/frontend/drone-app/build:/usr/share/nginx/html/static
    ports:
      - '2800:80'
    depends_on:
      - app
    networks:
      - web_nw

networks:
  web_nw:
    driver: bridge
